export type ButtonType = 'button' | 'submit' | 'reset'
export type Variant =
  | 'primary'
  | 'secondary'
  | 'success'
  | 'danger'
  | 'warning'
  | 'info'
  | 'light'
  | 'dark'
export type Size = 'sm' | 'md' | 'lg'
